module.exports = function(grunt){
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        typescript:{
            class:{
                generateTsConfig:true,
                src:['src/*.ts'],
                dest:'bin/browser/jsAFlag.js',
                options:{
                    module:'none',
                    target:'es6',
                    sourceMap:true,
                    removeComments:true,
                    declaration:true,
                }
            },
            npm:{
                generateTsConfig:true,
                src:['src/*.ts','src/npm/exports.ts'],
                dest:'bin/npm/AHref.js',
                options:{
                    module:'none',
                    target:'es6',
                    sourceMap:true,
                    removeComments:true,
                    declaration:true,
                }
            },
            watch:{
                generateTsConfig:true,
                src:['src/*.ts'],
                dest:'bin/browser/jsAFlag.js',
                options:{
                    module:'none',
                    target:'es6',
                    sourceMap:true,
                    removeComments:true,
                    declaration:true,
                    watch:{
                        atBegin:true
                    }
                }
            },
            npm_pkg:{
                generateTsConfig:true,
                src:['src/*.ts','src/npm/exports.ts'],
                dest:'build_npm/index.js',
                options:{
                    module:'none',
                    target:'es6',
                    sourceMap:false,
                    removeComments:true,
                    declaration:false,
                }
            }
        },
        copy:{
            npm_pkg:{
                files:[
                    {
                        expand:true,
                        src:['package.json'],
                        flatten:true,
                        dest:'build_npm/'
                    },
                    {
                        expand:true,
                        src:['tests/mocha/test.js'],
                        flatten:true,
                        dest:'build_npm/'
                    }
                ]
            }
        }
    })
    
    grunt.loadNpmTasks('grunt-typescript');
    grunt.loadNpmTasks('grunt-contrib-copy');
    
    grunt.registerTask('build-class',['typescript:class']);
    grunt.registerTask('build-npm',['typescript:npm']);
    grunt.registerTask('build-watch',['typescript:watch']);

    grunt.registerTask('npm_pkg',['typescript:npm_pkg','copy:npm_pkg']);

    grunt.registerTask('default',['build-watch']);
}